- README.md
This just removes an extra `}` in the README for DALL-E.
> Remove extraneous curly brace in README

- README.md
- lib/ruby/openai/client.rb
I started getting issues today on a project that org header was missing. I added it in the same way as access token it can be passed as an env variable or directly on class init.
> Adding Org Header

- .travis.yml
Remove .travis.yml file because this repo now uses GitHub Actions for CI.
> Remove the obsolete .travis.yml file

- lib/ruby/openai/client.rb
- lib/ruby/openai/files.rb
- lib/ruby/openai/finetunes.rb
- lib/ruby/openai/images.rb
This change also fixes the existing NPE on the cancel action.
I'm backporting these changes from my larger scale rewrite, because the latter is getting larger and diverting more substantially from the existing gem.
While this commit / PR doesn't contain any additional specs, I'd recommend that some unit tests be added (or pulled back from the rewrite branch) to ensure against regression.  The VCR-based specs are not sufficient as is.
This is an alternative to #142 , implementing the suggestion I made there.
It's worth noting that the only reason the existing specs are passing is because VCR is doing default matching - method and URI - and is not matching request headers or body.  So the content-type and the body are getting ignored.  I attempted to turn on matching there, but I got weird …
> Update the POST actions so that they use the correct Content-Type headers

- .circleci/config.yml
Ruby 3.2 was released on December 25th, 2022.  A few days later CircleCI added a `cimg` built with this Ruby.  Given that this is the latest release of Ruby, it should be included in the CI for the gem.  This PR adds the necessary CircleCI image.
I've runs specs locally against Ruby 3.2 and they pass.
> Adds Ruby 3.2 to the CircleCI configuration

- Gemfile.lock
When running `bundle ...` on the current Gemfile a warning:
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```
is generated.  This is a a result of an outdated `bundler`.  Updating the `bundler` in the `Gemfile.lock` resolves the issue.
> Upgrade bundler version used for bundling Gemfile to eliminate DidYouMean warning

- spec/spec_helper.rb
- spec/support/vcr_multipart_matcher.rb
This change ensures that VCR-based specs match not only the method and URI, but also the headers and body of the request.  Had this been in place earlier, all of the bugs resolved in 3.0.2 and 3.0.3 would have caused spec failures.
This includes code to handle the fact that the boundary used in multipart form posts changes randomly from request to request.
I opened a related issue on VCR - https://github.com/vcr/vcr/issues/960 .
> Adds body and headers matching for VCR

- README.md
- lib/openai.rb
- lib/openai/client.rb
- spec/openai/client/client_spec.rb
- spec/openai_spec.rb
This PR adds the ability to set the timeout (in seconds) for OpenAI requests. It can be configured by two ways:
1) Passing `request_timeout` named param when initializing the client. eg.
```ruby
OpenAI::Client.new(request_timeout: 25)
```
2) when configuring the gem. eg.
```ruby
OpenAI.configure do |config|
config.request_timeout = 25
end
```
The default value is 60 seconds, which is the default value of the `Net::HTTP` class
> adds the ability to configure the timeout for the OpenAI requests

- README.md
Fixed the whisper example in readme.md. Files must be opened in binary mode, otherwise it will not work.
> Whisper example: files must be opened in binary mode

- README.md
The current sample value in README actually doesn't work, and results in url like `oai.hconeai.comv1`. The trailing slash is essential.
> Fix uri_base sample value in README

- README.md
- spec/spec_helper.rb
- Makes specs always hit the API if a token is found, either in ENV or passed in explicitly
- Allow specs to run even if the user does not have `OPENAI_ACCESS_TOKEN` in ENV, as suggested in [https://github.com/alexrudall/ruby-openai/pull/214](https://github.com/alexrudall/ruby-openai/pull/214)
> If token found, make specs always hit the actual API

- README.md
The links aren't broken (they do redirect to `platform.openai.com`), but they're outdated.
> Update beta.openai.com link in README

- lib/openai/http.rb
Due to the way that Ruby closures work for procs, it's quite limiting to limit the stream interface to just Proc objects. This PR makes a tiny change so that callable objects work too. (Anything that implements a `call` method.)
Here's a simple example from my project MagmaChat:
```
class StreamProcessor
def initialize(bot:, buffer:, message:)
Rails.logger.info "💦💦💦 initializing stream processor for message: #{message} 💦💦💦"
@buffer = buffer
@message = message
end
def call(chunk, _bytesize=nil)
Rails.logger.info "💦💦💦 streaming chunk: #{chunk} (#{_bytesize} bytes) 💦💦💦"
if new_content = chunk.dig("choices", 0, "delta", "content")
@buffer << new_content
ActiveRecord::Base.logger.silence do
@message.update(content: @message.content + new_content)
end
end
end
end
```
> stream option should take any callable not just a proc

- lib/openai.rb
- lib/openai/http.rb
- spec/openai/client/http_spec.rb
**Problem**
Resolves #231. We would like to use `ruby-openai` with Microsoft Azure OpenAI, however its endpoints and authentication headers are slightly different, making it impossible currently to use this gem.
**Solution**
This PR adds a configuration setting `api_type`, which can be set to `:azure`, similar to how https://github.com/openai/openai-python supports Microsoft Azure.
**Alternatives**
I'm aware of the changes being worked on in https://github.com/alexrudall/ruby-openai/pull/150, it might be possible to create a subclass of `OpenAI::Client` instead once this has been implemented. I'm happy to rebase and refactor this PR once this is merged.
**Additional context**
- Microsoft Azure currently only supports completions and embeddings, so these are the only endpoints implemented …
> Add Microsoft Azure support

- README.md
Add the standard weather example for function calling to the README
> Add functions example to README

- README.md
This is a very small change, but while trying out the sampling code in the README, I noticed that the name of the embedded model is not recommended.
> We recommend using text-embedding-ada-002 for nearly all use cases. It’s better, cheaper, and simpler to use. Read the [blog post announcement](https://openai.com/blog/new-and-improved-embedding-model).
https://platform.openai.com/docs/guides/embeddings/what-are-embeddings
The official site also recommends using text-embedding-ada-002.
> Update model name to ext-embedding-ada-002 in README.md

- README.md
- lib/openai.rb
- spec/openai_spec.rb
It can be useful to estimate the token count of some text before sending it to OpenAI. This PR adds an `OpenAI.rough_token_count` class method which does this.
To perform the estimation, it uses the two "helpful rules of thumb" in OpenAI's [docs](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them) and takes the arithmetic average.
The empty string returns 0, and any other string returns an integer greater than 0.
This is a rewrite of #306 to remove the Tiktoken functionality and change the interface as requested.
> Add OpenAI.rough_token_count class method

- Gemfile.lock
- lib/openai/http.rb
- ruby-openai.gemspec
- spec/openai/client/http_spec.rb
Follow up to #332
1. Switch to using `event_stream_parser`, a spec-compliant event stream parser (that I recently published)
2. ~~The stream proc now receives an optional second argument for any errors encountered during parsing -- consumers should know, instead of these errors being silently ignored by this library~~
3. Explicitly check for `"[DONE]"` chunks.
4. ~~Remove bits about errors OpenAI does not send~~
5. ~~Tweak bit about token usage in streams (it's not a public feature yet)~~
6. Check HTTP response code and only try to parse the body as an error JSON if it's not OK.
> Proper SSE parsing

- README.md
- Calling `client.files.upload` already returns the response as a Hash so we should not call `.body` on the response.
> :memo: fix an small error in the README.md documentation

- lib/openai/http.rb
- spec/openai/client/http_spec.rb
When calling the `chat` method, the parameters used when calling it are being altered, specifically the parameters[:stream] entry:
```ruby
parameters = {
model: "gpt-3.5-turbo", # Required.
messages: [{ role: "user", content: "Describe a character called Anna!"}], # Required.
temperature: 0.7,
stream: proc do |chunk, _bytesize|
print chunk.dig("choices", 0, "delta", "content")
end
}
client.chat(parameters: parameters)
puts parameters[:stream]
```
This can cause bugs as parameters should remain unchanged, we noticed it when we tried retrying the request on some OpenAi network failures, we called the method again with the same parameters and noticed streaming wouldn't work then.
**Impact**: This change does not affect the external behavior of the chat method but ensures parameter integrity …
> Fix Maintain Unchanged Hash Parameter in Method json_post

- lib/openai/http.rb
- spec/fixtures/cassettes/gpt-3_5-turbo_streamed_chat_with_json_error_response.yml
- spec/openai/client/chat_spec.rb
Fixes #357
Gracefully handle the case where an HTTP error response may not have valid JSON in its body e.g.:
- OpenAI is having a bad day an returns a 500 Internal Server Error
- Some other network element like a proxy is returning some 4xx or 5xx.
> Handle case where error response body may not be JSON

- README.md
- lib/openai/client.rb
- lib/openai/http.rb
- spec/fixtures/cassettes/gpt-3_5-turbo_function_call_chat.yml
- spec/openai/client/chat_spec.rb
- spec/openai/client/client_spec.rb
- Add test that error messages are included in Faraday response body
- Add ability to pass Faraday config block to client
> Add ability to pass Faraday config block to Client

- lib/openai/files.rb
Currently all files are validated on upload so it is impossible to use PDFs for assistants
This small fix now allows other types
> Files for assistants can now be PDFs,... as we only validate .jsonl files

- README.md
Threads, Messages and Runs/Steps done.
> Completed README additions for Assistants API

- README.md
- spec/fixtures/cassettes/images_edit_image_png_A_solid_red_Ruby_on_a_blue_background.yml
- spec/fixtures/cassettes/images_generate_A_baby_sea_otter_cooking_pasta_wearing_a_hat_of_some_sort.yml
- spec/fixtures/cassettes/images_generate_A_lion_cooking_pasta_wearing_a_hat_of_some_sort.yml
- spec/fixtures/cassettes/images_generate_A_springer_spaniel_cooking_pasta_wearing_a_hat_of_some_sort.yml
- spec/fixtures/cassettes/images_variations_image_png.yml
- spec/openai/client/images_spec.rb
Hello @alexrudall. I've created this PR to _make a start_ on making the DALLE 3 available in the gem. 
I think this PR has some way to go. In particular, I'm not sure how/if changes should be made to `lib/images.rb`. 
I've made an addition to the spec for images. In particular I've broken out the functionality of both DALLE2 and DALLE3. At the moment there is only the ability to generate images in DALLE3 hence the omission of edits and variations. 
I added a new tests for DALL·E 3 and my VCR recording. 
I've also made a start on updating the README.md. 
If you could let me know if this is appropriate or what else might need done I will be happy to take this as far as I can.
> Add  DALL·E 3 functionality

- README.md
I believe that some significant portion of `#transcribe` function might be using it in languages other than English.
For them it might be handy to clearly see that "language" attribute is (implicitly) supported so that they don't need to check `Create transcription` documentation at https://platform.openai.com/docs/api-reference/audio/createTranscription?lang=node.
[X] I checked locally that it works with explicit "en" value and a few other languages
> Update README.md - mention "language" attribute explicitely in #transcribe

- lib/openai/threads.rb
The [Threads API](https://platform.openai.com/docs/api-reference/threads/createThread) doesn't expose a method to get the list of threads. It isn't listed on the official documentation:
Trying that endpoint returns the following error:
```
"OpenAI HTTP Error (spotted in ruby-openai 6.3.1): {"error"=>{"message"=>"Your request to GET /v1/threads must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.", "type"=>"invalid_request_error", "param"=>nil, "code"=>"missing_scope"}}"
```
> Remove inexistent threads#list API

- README.md
`client.completions` is deprecated, but was still used in the example section for using fine tuned models. This just updates the readme to use `client.chat` and the appropriate param and response attributes.
> Update fine tune README section for completion deprecation

- README.md
- lib/openai/client.rb
- spec/fixtures/cassettes/gpt-3_5-turbo-instruct_completions_once_upon_a_time.yml
- spec/openai/client/completions_spec.rb
This change addresses the issue discussed [here](https://github.com/alexrudall/ruby-openai/issues/381). With the current state, it is impossible to use `gpt-3.5-turbo-instruct` without the completions endpoint or downgrading the gem version.
> Added /completions endpoint back to support gpt-3.5-turbo-instruct

- spec/fixtures/cassettes/messages_list.yml
- spec/fixtures/cassettes/messages_list_thread_setup.yml
- spec/openai/client/messages_spec.rb
I noticed there's missing test coverage for `messages.list`.
This PR adds the missing spec, as well as the missing cassettes.
Tests pass and the cassette response data is authentic.
Hope this helps folks needing to better understand the response format for the `messages.list` call :)
----
> Add a missing spec for messages#list

- README.md
- lib/openai/http.rb
- lib/openai/messages.rb
- lib/openai/run_steps.rb
- lib/openai/runs.rb
- spec/fixtures/cassettes/messages_list.yml
- spec/fixtures/cassettes/messages_list_thread_setup.yml
- spec/fixtures/cassettes/run_steps_list.yml
- spec/fixtures/cassettes/run_steps_list_assistant_setup.yml
- spec/fixtures/cassettes/run_steps_list_run_setup.yml
- spec/fixtures/cassettes/run_steps_list_thread_setup.yml
- spec/fixtures/cassettes/runs_list.yml
- spec/fixtures/cassettes/runs_list_assistant_setup.yml
- spec/fixtures/cassettes/runs_list_run_setup.yml
- spec/fixtures/cassettes/runs_list_thread_setup.yml
- spec/openai/client/messages_spec.rb
- spec/openai/client/run_steps_spec.rb
- spec/openai/client/runs_spec.rb
Teach the `client.runs.list` endpoint about a `parameters:` kwarg. That kwarg is passed to the underlying GET request.
I would like to check the latest run for a thread, and it seems like the best way to do this is to list the runs for a thread limited to 1.
> Teach runs list endpoints to use parameters

- README.md
This change adds a small update to the README file that documents how to use the `messages.modify` method to update the metadata for an assistant run's message.
> add documentation that shows how to update a message

- README.md
This change addresses the [issue](https://github.com/alexrudall/ruby-openai/issues/452).  `tool_calls` is an array, so we must access the first index when retrieving values.  Furthermore, the `tool_choice` key was left out of the documentation, causing a variance in behavior.
> Update function calling section of README

- lib/openai/http.rb
- spec/openai/client/http_spec.rb
- Replacement for #395 - if the API version is already in the uri_base, don't add it again
- Example: [Portkey](https://portkey.ai/docs/api-reference/gateway-for-other-apis#you-can-call-the-endpoint-by-adding-it-after-https-api.portkey.ai-v1)
> Handle API version in base URI

- README.md
- Fix up some errors in the Assistants README
- Encourage logging errors
> Assistants README fixes

- README.md
I had to poke around the code to make sure that the additional parameters for the audio endpoint were supported. They are since ruby just passes them straight on through. I figured it's worth updating the README to reflect it just like the other sections which also mention the optional parameters. This should save someone a little time in the future.
> Update README audio section to show full parameter support

- .gitignore
- lib/openai/http_headers.rb
- spec/openai/client/http_spec.rb
I've looked at using groq via langchain -> ruby-openai and was seeing a warning about me not setting `OpenAI-Organization`. If I run `.compact` on the headers, the warning seems to go away.
> If being used for Groq, skip OpenAI-Organization header

- README.md
- lib/openai/batches.rb
- spec/openai/client/batches_spec.rb
Closes #490
I added a new test that creates a batch first, so we can test the `after` parameter. Without an existing batch, it would return an error.
**Edit:** Looks like there's some Rubocop linting issues. I wasn't able to get Rubocop running so perhaps @alexrudall you can take care of these as they seem auto-fixable.
**Edit 2:** Okay, I fixed the Rubocop linting issues. Only thing left to make the test pass is to record a new VCR cassette. I'm not comfortable getting my company details in there, so can you do it @alexrudall? I already checked locally, and the test pass with a valid API key.
> Add parameters support to batches.list and update README to include /v1/embeddings Batches support

- README.md
OpenAI introduced a new chat parameter that allows you to get usage information at the end of a streamed response.  This updates the README with further instructions on how to accomplish this and the format of the response.
> Update README.md with usage info while streaming

- lib/openai/client.rb
- spec/openai/client/client_spec.rb
Updates the `.inspect` method for `OpenAI::Client` to obfuscate sensitive values by replace them with `[REDACTED]`. This should prevent accidental logging of API keys, etc.
Resolves alexrudall/ruby-openai#513
> Hide sensitive info when inspecting client

- lib/openai/files.rb
- spec/openai/client/client_spec.rb
`purpose` is currently accepted but the gem doesn't allow for passing it in.
https://platform.openai.com/docs/api-reference/files/list#files-list-purpose
> Pass parameters through to List files endpoint

- README.md
We're using Velvet instead of Helicone on our rails app ([usefind.ai](https://usefind.ai)), so I wanted to update the docs to reference that. Setup is pretty much the same as helicone.
> Update README.md with Velvet config link

- .gitignore
- README.md
> Add Assistant Vision example to README

- README.md
Hi Alex, I saw your tweet this morning about using the OpenAI assistants API. Very exciting!
When I looked at the tweet, I noticed that it lacked syntax highlighting.
This PR has 2 commits. The first adds languages to code blocks that were missing them (except one related to an ENV file). I think the language commit is very low risk and would help with doc readability.
While I was in there, I also went through and made a second commit to try to reformat the code examples to reduce leading whitespace and consistently format. I think by doing this:
- more of each example will be visible to folks who are viewing the README in their browser since leading whitespace is trimmed
- the README will be easier to skim through due to the consistency of formatting
- it will be easier to copy-paste, …
> Quick readme tweaks

- lib/openai/http.rb
- spec/fixtures/cassettes/files_fetch_image.yml
- spec/fixtures/cassettes/files_fetch_image_poll.yml
- spec/fixtures/cassettes/files_fetch_image_retrieve.yml
- spec/fixtures/cassettes/files_fetch_image_upload.yml
- spec/fixtures/cassettes/mocks/gpt-3_5-turbo_streamed_chat_with_error_response.yml
- spec/fixtures/cassettes/mocks/gpt-3_5-turbo_streamed_chat_with_json_error_response.yml
- spec/fixtures/cassettes/mocks/http_get_with_error_response.yml
- spec/openai/client/chat_spec.rb
- spec/openai/client/files_spec.rb
- spec/openai/client/http_spec.rb
[BREAKING CHANGE]
- Try to parse all responses as JSON
- If parsing JSON fails, return the original response as-is
- Reproduction and fix for [https://github.com/alexrudall/ruby-openai/pull/544](https://github.com/alexrudall/ruby-openai/pull/544)
Update gemfile:
```
gem 'ruby-openai', git: 'git://github.com/alexrudall/ruby-openai.git', branch: 'fix/non-json-content'
```
Run `bundle install`
#277 
#314
#416
#421 
#562 
#474
#504 
#540 
#544
> Fixes for various JSON/non-JSON content issues

- lib/openai/client.rb
I see this warning on MRI 3.3:
```console
ruby/3.3.7/lib/ruby/gems/3.3.0/gems/ruby-openai-6.3.1/lib/openai/client.rb:14: warning: `*' interpreted as argument prefix
```
Using explicit parenthesis fixes the issue.
> Fix ruby warning: * interpreted as argument prefix

- README.md
- lib/openai/vector_stores.rb
- spec/fixtures/cassettes/vector_stores_search.yml
- spec/fixtures/cassettes/vector_stores_search_setup.yml
- spec/openai/client/vector_stores_spec.rb
Adds the ability to query a vector store using the search endpoint, as can be found in the [OpenAI documentation
](https://platform.openai.com/docs/api-reference/vector-stores/search)
> Add search method to vector stores

- README.md
Google Gemini Pro has an OpenAI-compatible API that works with this gem. I added a section in the README showing how to configure your gem to use Gemini.
* [X ] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [ X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [ X] Have you added an explanation of what your changes do and why you'd like us to include them?
> Update README to include Gemini instructions

- README.md
As per: https://github.com/alexrudall/ruby-openai/pull/502#issuecomment-2404652410 @alexrudall prefers to use the existing block form of `OpenAI::Client.new` to configure the Faraday middleware with a proxy.
1. Changes the `##### Faraday middleware` section to support multiple use cases for passing a block to `OpenAI::Client.new`.
2. Adds an example which configures Faraday middleware with a web debugging proxy.
Obviates:
- https://github.com/alexrudall/ruby-openai/pull/502
> docs(readme): add Faraday proxy example

- README.md
> Update README.md for reasoning model
