alexrudall/ruby-openai

.rubocop.yml, CHANGELOG.md, Gemfile.lock, README.md, lib/ruby/openai.rb, lib/ruby/openai/client.rb, lib/ruby/openai/files.rb, lib/ruby/openai/version.rb, pull_request_template.md, spec/fixtures/cassettes/davinci_search_happy.yml, spec/fixtures/cassettes/files_delete.yml, spec/fixtures/cassettes/files_list.yml, spec/fixtures/cassettes/files_retrieve.yml, spec/fixtures/cassettes/files_upload.yml, spec/fixtures/cassettes/files_upload_search.yml, spec/fixtures/files/puppy.jsonl, spec/ruby/openai/client/completions_spec.rb, spec/ruby/openai/client/files_spec.rb, spec/ruby/openai/client/search_spec.rb, spec/spec_helper.rb
=> Add file upload

CHANGELOG.md, Gemfile.lock, README.md, lib/ruby/openai/client.rb, lib/ruby/openai/version.rb, spec/fixtures/cassettes/ada_answers_documents_which_puppy_is_happy_.yml, spec/fixtures/cassettes/davinci_answers_file_which_puppy_is_happy_.yml, spec/fixtures/cassettes/files_upload_answers.yml, spec/ruby/openai/client/answers_spec.rb, spec/ruby/openai/client/search_spec.rb
=> Add Answers endpoint

CHANGELOG.md, lib/ruby/openai/files.rb, lib/ruby/openai/version.rb, spec/fixtures/files/errors/missing_quote.jsonl, spec/ruby/openai/client/files_spec.rb
=> Add JSONL validation

README.md
=> Add Codeclimate

CHANGELOG.md, README.md, lib/ruby/openai/client.rb, lib/ruby/openai/version.rb, spec/ruby/openai/client/search_spec.rb
=> Update search to allow more parameters

CHANGELOG.md, Gemfile.lock, README.md, lib/ruby/openai/client.rb, lib/ruby/openai/files.rb, lib/ruby/openai/version.rb, spec/fixtures/cassettes/ada_classifications_examples_it_is_a_raining_day_.yml, spec/fixtures/cassettes/curie_classifications_file_movie_is_very_good.yml, spec/fixtures/cassettes/files_upload_classifications.yml, spec/fixtures/files/train.jsonl, spec/ruby/openai/client/classifications_spec.rb
=> Add Classifications

.circleci/config.yml, .rubocop.yml, CHANGELOG.md, README.md, lib/ruby/openai/version.rb, ruby-openai.gemspec
=> Add test matrix

README.md
It took me way too long to figure out the gem's name. 😅
=> Include `require` statements into README

README.md, spec/fixtures/cassettes/ada-instruct-beta_completions_once_upon_a_time.yml, spec/fixtures/cassettes/babbage-instruct-beta_completions_once_upon_a_time.yml, spec/fixtures/cassettes/content-filter-alpha_completions_a_very_rude_word_.yml, spec/fixtures/cassettes/curie-instruct-beta-v2_completions_once_upon_a_time.yml, spec/fixtures/cassettes/cushman-codex_completions_def_hello_world_puts.yml, spec/fixtures/cassettes/davinci-codex_completions_def_hello_world_puts.yml, spec/fixtures/cassettes/davinci-instruct-beta-v3_completions_once_upon_a_time.yml, spec/ruby/openai/client/completions/base_spec.rb, spec/ruby/openai/client/completions/codex_spec.rb, spec/ruby/openai/client/completions/content_filter_spec.rb, spec/ruby/openai/client/completions/instruct_spec.rb, spec/ruby/openai/client/completions_spec.rb
- Add instruct engines to spec
- Add codex engines to spec
- Add content-filter spec
- Add new engines to README
=> Add docs and tests for new engines

README.md, lib/ruby/openai.rb, lib/ruby/openai/client.rb, lib/ruby/openai/engines.rb, spec/fixtures/cassettes/engines_list.yml, spec/fixtures/cassettes/engines_retrieve.yml, spec/ruby/openai/client/engines_spec.rb
=> Add Engines endpoints

.circleci/config.yml
=> Add Ruby 3.1 to tests

README.md
=> Update README tagline

README.md
=> Update a couple of engine names

README.md, lib/ruby/openai/client.rb, spec/fixtures/cassettes/moderations_i_m_worried_about_that_.yml, spec/ruby/openai/client/moderations_spec.rb
- Add Moderations endpoint
- Reorder README to match docs
- Add Moderations to README
=> Add Moderations endpoint

README.md, lib/ruby/openai/client.rb, spec/fixtures/cassettes/text-davinci-edit-001_moderations_what_day_of_the_wek_is_it_.yml, spec/ruby/openai/client/edits_spec.rb
- Add Edits endpoint
- Add Edits to README
=> Add Edits endpoint

.circleci/config.yml, .rubocop.yml, ruby-openai.gemspec
=> Remove support for Ruby 2.5

CHANGELOG.md, Gemfile.lock, lib/ruby/openai/version.rb
=> Release 2.0.0

README.md
=> Fix README order

CHANGELOG.md, lib/ruby/openai/client.rb, lib/ruby/openai/version.rb
=> Deprecate #answers and #classifications

Gemfile.lock, README.md
=> Bump version

README.md, lib/ruby/openai/client.rb, lib/ruby/openai/engines.rb, lib/ruby/openai/files.rb, lib/ruby/openai/finetunes.rb, lib/ruby/openai/images.rb, lib/ruby/openai/models.rb, spec/fixtures/cassettes/text-ada-001_answers_documents_which_puppy_is_happy_.yml, spec/spec_helper.rb
- Add Organization ID to all calls
- Rerun spec with Organization ID
=> Add Organization ID to all requests

README.md
=> Tweak README intro

CHANGELOG.md, Gemfile.lock, lib/ruby/openai/version.rb
=> Release 2.3.0

.rubocop.yml, Gemfile, Gemfile.lock, README.md, lib/ruby/openai.rb, lib/ruby/openai/client.rb, lib/ruby/openai/engines.rb, lib/ruby/openai/files.rb, lib/ruby/openai/finetunes.rb, lib/ruby/openai/images.rb, lib/ruby/openai/models.rb, ruby-openai.gemspec, spec/fixtures/cassettes/text-ada-001_completions_once_upon_a_time.yml, spec/ruby/openai_spec.rb, spec/spec_helper.rb
- Add Config object
- Remove dotenv
- Addresses https://github.com/alexrudall/ruby-openai/issues/123
=> Replace dotenv with config object

lib/ruby/openai/finetunes.rb, lib/ruby/openai/images.rb, spec/fixtures/cassettes/finetunes_create.yml, spec/fixtures/cassettes/images_generate_A_baby_sea_otter_cooking_pasta_wearing_a_hat_of_some_sort.yml
- Fix for https://github.com/alexrudall/ruby-openai/issues/139
=> Fix broken image and finetune endpoints

README.md, spec/spec_helper.rb
- Add way to quickly run all specs without VCR
- Add spec run cost estimate
=> Add quick way to run specs without VCR

spec/ruby/openai/client/edits_spec.rb
=> Tweak spec to be more robust

README.md
[Feat] Document Images size parameters
=> [Feat] Document Images size parameters

README.md
=> Tweak image size on README

CHANGELOG.md, Gemfile.lock, lib/ruby/openai/version.rb
=> Bump to 3.0.3

README.md, lib/ruby/openai/finetunes.rb, spec/fixtures/cassettes/finetunes_delete.yml, spec/fixtures/cassettes/finetunes_delete_create.yml, spec/fixtures/cassettes/finetunes_delete_retrieve.yml, spec/ruby/openai/client/finetunes_spec.rb
- Addresses https://github.com/alexrudall/ruby-openai/issues/168
- Add Finetune#delete method
- Update README
=> Add Finetune#delete

Gemfile.lock, ruby-openai.gemspec
- Not sure of need for upper limit, it seems to cause problems here: https://github.com/alexrudall/ruby-openai/issues/160
=> Remove upper limit on httparty version

Gemfile.lock
=> Bump Bundler version

spec/support/vcr_multipart_matcher.rb
=> Swap Ruby 3 `except` for backwards-compatible `reject`

README.md
=> Update README.md with ad link

README.md
=> Remove ad from README

CHANGELOG.md, Gemfile.lock, lib/ruby/openai/version.rb
=> Bump to 3.1.0

README.md, lib/ruby/openai/files.rb, spec/fixtures/cassettes/files_content.yml, spec/fixtures/cassettes/files_content_upload.yml, spec/ruby/openai/client/files_spec.rb
=> Add Files#content

CHANGELOG.md, Gemfile.lock, lib/ruby/openai/version.rb
=> Bump to 3.2.0

CHANGELOG.md, Gemfile.lock, README.md, lib/openai/client.rb, lib/openai/version.rb, spec/fixtures/cassettes/gpt-3_5-turbo-0301_chat.yml, spec/fixtures/cassettes/gpt-3_5-turbo_chat.yml, spec/openai/client/chat_spec.rb
=> Add ChatGPT endpoint

README.md, spec/openai/client/audio_spec.rb
=> Bump to 3.5.0

README.md
=> Improve ChatGPT docs

README.md, lib/openai.rb, spec/openai/client/client_spec.rb, spec/openai_spec.rb
=> Increase default timeout to 120 seconds

spec/fixtures/cassettes/finetunes_delete.yml, spec/fixtures/cassettes/finetunes_delete_create.yml, spec/fixtures/cassettes/finetunes_files_upload_.yml, spec/openai/client/finetunes_spec.rb
=> Update spec to match new error message

CHANGELOG.md, Gemfile.lock, lib/openai/version.rb
=> Bump to 3.6

README.md, spec/openai_spec.rb
- Update config spec
- Add [Helicone](https://www.helicone.ai/) to README
=> add helicone to readme

README.md
=> Tweak README spacing on couple of examples

README.md
=> Add link to Promptheart

README.md
=> Remove Promptheart

README.md
Fix maintainability badge url in README.md
=> Fix maintainability badge url in README.md

README.md
=> Remove Codeclimate

lib/openai/client.rb, spec/openai/client/chat_spec.rb, spec/openai/client/client_spec.rb
This PR will change how streaming parses chunks of data. Instead of "cleaning" up the data and parsing it as a large multi-line chunk, it reads data chunks by scanning with a regular expression and for each capture it passes that to the users proc.
=> Improved stream parsing

README.md
=> Add twitter link

.gitignore
=> Update .gitignore file.

README.md, lib/openai.rb, lib/openai/client.rb, lib/openai/http.rb, spec/openai_spec.rb
Add extra_headers for cache proxy
=> Extra headers

CHANGELOG.md, Gemfile.lock, lib/openai/version.rb
=> Bump to 4.3

CHANGELOG.md, Gemfile.lock, lib/openai.rb, lib/openai/client.rb, lib/openai/http.rb, lib/openai/version.rb
- Don't overwrite config extra-headers when making a client
- Fixes #307
=> "Don't overwrite extra headers"

README.md
Formats README markdown codeblock for shell installation instructions
=> Formats README installation instructions

README.md
=> Add note about Helicone streaming

README.md
=> Add RailsAI to README

README.md
=> Add links to other gems to README

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
=> Add devcontainer for Docker development

.github/FUNDING.yml
=> Add sponsorship badge

Gemfile.lock, ruby-openai.gemspec
=> Loosen event_stream restrictions

README.md
=> Add note that gpt-4 uses current version of GPT4

README.md
=> Clean up hire me link

README.md
=> Add Vision example to README

README.md
=> Switch README version badge to update quicker

README.md
=> Add JSON mode to the README

README.md
=> Add JSON mode streaming example

README.md, ruby-openai.gemspec
=> Tweak emojis

README.md
=> Add docs for extra extra headers

ruby-openai.gemspec
=> Add link to sponsor page

README.md, lib/openai/runs.rb, spec/fixtures/cassettes/runs_create_thread_and_run.yml, spec/openai/client/runs_spec.rb
- Support API create a thread and run in one request
```ruby
OpenAI::Client.new.runs.create_thread_and_run(
parameters: {
assistant_id: assistant_id,
thread: {
messages: [{ role: "user", content: "Describe a character called Anna!", file_ids: [] }]
}
}
)
```
=> Support API Create a thread and run it in one request.

README.md
=> Tiny formatting fix

README.md
Update the README to include a more accurate Groq URI base
=> Update Groq URI base

README.md
=> Fix Ollama model

lib/openai/messages.rb, spec/fixtures/cassettes/messages_delete.yml, spec/fixtures/cassettes/messages_delete_message_setup.yml, spec/fixtures/cassettes/messages_delete_thread_setup.yml, spec/openai/client/messages_spec.rb
Adds the `messages.delete` endpoint handler.
=> Add messages delete handler

README.md
=> Add note to README to indicate that assistants are reusable

CHANGELOG.md, Gemfile.lock, README.md, lib/openai.rb, lib/openai/client.rb, lib/openai/compatibility.rb, lib/openai/usage.rb, lib/openai/version.rb, spec/fixtures/cassettes/usage_audio_speeches.yml, spec/fixtures/cassettes/usage_audio_transcriptions.yml, spec/fixtures/cassettes/usage_completions.yml, spec/fixtures/cassettes/usage_costs.yml, spec/fixtures/cassettes/usage_embeddings.yml, spec/fixtures/cassettes/usage_images.yml, spec/fixtures/cassettes/usage_moderations.yml, spec/fixtures/cassettes/usage_vector_stores.yml, spec/openai/client/client_spec.rb, spec/openai/client/usage_spec.rb, spec/spec_helper.rb
- Add support for OPENAI_ADMIN_TOKEN to allow for administrative endpoints to be called.
- Add Usage endpoints.
=> Add Admin tokens and Usage endpoints

README.md, spec/fixtures/cassettes/deepseek_deepseek-chat_streamed_chat.yml, spec/openai/client/chat_spec.rb
- **Add Deepseek spec**
- **Fix warning**
- **Add Deepseek to README**
=> Add Deepseek to docs

lib/openai/models.rb
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
This allows programmatic management of fine tune models which was needed for my use-case
=> exposing the delete method on open ai models

README.md
=> Add Sponsors heading to README

.gitignore
=> Add Incident Response Plan

README.md
=> Sponsors/Add SerpApi

CHANGELOG.md
=> Fix incorrect attribution in changelog
